
model: 'DSSM'
dataset: 'mind_small_tfidf_merged'

# general 
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
checkpoint_dir: saved
show_progress: True
save_dataset: False
dataset_save_path: None
save_dataloaders: False
dataloaders_save_path: None
log_wandb: True


load_col:  
    inter: ['user_id', 'item_id', 'label', 'timestamp'] 
    item: ['item_id','category', 'sub_category', 'title']
# LABEL_FIELD: 'label'
#numerical_features: ['title_tf_idf']

#benchmark_filename: ['train','dev', 'dev']
repeatable: False
epochs: 30
train_batch_size: 512
eval_batch_size: 1024
embedding_size: 1
learning_rate: 0.0001
weight_decay: 0.00001
mlp_hidden_size: [256, 256, 256]





eval_args:
    split:
        RS: [0.68, 0.32,0] 
    group_by: None
    order: 'TO'
    mode: 'uni10'
eval_step: 7

metrics: ['Recall', 'MAP', 'NDCG', 'Hit', 'Precision', 'MRR']
topk: 10
valid_metric: 'NDCG@10'
metric_decimal_place: 4
