
# general 
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
checkpoint_dir: saved
show_progress: True
save_dataset: False
dataset_save_path: None
save_dataloaders: False
dataloaders_save_path: None
log_wandb: False

load_col:  
    inter: ['user_id', 'item_id', 'label', 'timestamp'] 
LABEL_FIELD: 'label'
TIME_FIELD: timestamp
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
# benchmark_filename: ['train','val', 'dev']

repeatable: True

# training 

epochs: 50
train_batch_size: 4096
eval_batch_size: 4096
embedding_size: 32
eval_args:
    mode: 'pop10'
    #'uni10'

train_neg_sample_args: 
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full


metrics: ['Recall', 'MAP', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: 'NDCG@10'
metric_decimal_place: 4
